import Head from "next/head";
import React, { useEffect } from "react";
import styles from '../styles/Home.module.css'
import bg from '../public/shapes.jpg'
import Link from 'next/link'

let user: {[k: string]: any} = {}

class Home extends React.Component {
  state = {
    username : ""
  }

  componentDidMount(): void {
    if (typeof window !== 'undefined') {
      const user = sessionStorage.getItem("active-user");
      this.setState({username : user});
    }
  }

  render(): React.ReactNode {
    return (
      <>
        <Head>
          <title>Sign in</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main} style={{
          backgroundImage: `url(${bg.src})`,
          width: '100%',
          height: '100%',
        }}>
          
          <h1>Good evening, {this.state.username}.</h1>

          <p><Link href="/" onClick={() => sessionStorage.clear()}>Sign out</Link></p>

        </main>
      </>
    )
  }
}

export default Home;
