import Head from "next/head";
import React, { useEffect, useState } from "react";
import styles from '../styles/Home.module.css'
import bg from '../public/shapes.jpg'
import Link from 'next/link'
import Note from "../components/Note";

const Home: React.FC = () => {
  const [username, setUsername] = useState("");
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [age, setAge] = useState(0);

  let user;

  useEffect(() => {
    if (typeof window !== 'undefined') {
      setUsername(sessionStorage.getItem("username") || "");
      setFirstName(sessionStorage.getItem("firstName") || "");
      setLastName(sessionStorage.getItem("lastName") || "");
      setAge(parseInt(sessionStorage.getItem("age") || "0"));
      user = firstName || username;
      console.log(username);
      console.log(firstName);
      console.log(lastName);
      console.log(age);
    }
  }, []);

    return (
      <>
        <Head>
          <title>Home</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main} style={{
          backgroundImage: `url(${bg.src})`,
          width: '100%',
          height: '100%',
        }}>
          
          <h1>Good evening, {username}.</h1>

          <div className={styles.box}>
            <Note title="LinkedIn" text="Studying Computer Science and Mathematics via Lehigh University's IDEAS program. Always hungry to learn more and explore new things. Looking for Summer 2023 internship opportunities." />
            <Note title="LinkedIn" text="Studying Computer Science and Mathematics via Lehigh University's IDEAS program. Always hungry to learn more and explore new things. Looking for Summer 2023 internship opportunities." />
            <Note title="LinkedIn" text="Studying Computer Science and Mathematics via Lehigh University's IDEAS program. Always hungry to learn more and explore new things. Looking for Summer 2023 internship opportunities." />
            <Note title="LinkedIn" text="Studying Computer Science and Mathematics via Lehigh University's IDEAS program. Always hungry to learn more and explore new things. Looking for Summer 2023 internship opportunities." />
            <Note title="LinkedIn" text="Studying Computer Science and Mathematics via Lehigh University's IDEAS program. Always hungry to learn more and explore new things. Looking for Summer 2023 internship opportunities." />
            <Note title="LinkedIn" text="Studying Computer Science and Mathematics via Lehigh University's IDEAS program. Always hungry to learn more and explore new things. Looking for Summer 2023 internship opportunities." />
            <Note title="LinkedIn" text="Studying Computer Science and Mathematics via Lehigh University's IDEAS program. Always hungry to learn more and explore new things. Looking for Summer 2023 internship opportunities." />
            <Note title="LinkedIn" text="Studying Computer Science and Mathematics via Lehigh University's IDEAS program. Always hungry to learn more and explore new things. Looking for Summer 2023 internship opportunities." />
            <Note title="LinkedIn" text="Studying Computer Science and Mathematics via Lehigh University's IDEAS program. Always hungry to learn more and explore new things. Looking for Summer 2023 internship opportunities." />
            <Note title="LinkedIn" text="Studying Computer Science and Mathematics via Lehigh University's IDEAS program. Always hungry to learn more and explore new things. Looking for Summer 2023 internship opportunities." />
            <Note title="LinkedIn" text="Studying Computer Science and Mathematics via Lehigh University's IDEAS program. Always hungry to learn more and explore new things. Looking for Summer 2023 internship opportunities." />
            <Note title="LinkedIn" text="Studying Computer Science and Mathematics via Lehigh University's IDEAS program. Always hungry to learn more and explore new things. Looking for Summer 2023 internship opportunities." />
            <Note title="LinkedIn" text="Studying Computer Science and Mathematics via Lehigh University's IDEAS program. Always hungry to learn more and explore new things. Looking for Summer 2023 internship opportunities." />
            <Note title="LinkedIn" text="Studying Computer Science and Mathematics via Lehigh University's IDEAS program. Always hungry to learn more and explore new things. Looking for Summer 2023 internship opportunities." />
          </div>

          <p><Link href="/" onClick={() => sessionStorage.clear()}>Sign out</Link></p>

        </main>
      </>
    )
}

export default Home;
