import React from 'react'
import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/NoUser.module.css'
import bg from '../public/shapes.jpg'
import Popup from '../components/Popup'

class Login extends React.Component {
  // store user inputs in state
  state = {
    user: {
      username: "",
      password: ""
    },
    error: false
  }

  // check db for user/pass pair
  // admit entry if it exists, reject otherwise
  login = async () => {
    try {
      const res = await fetch('api/query', {
        method: 'POST',
        headers: {
          'Content-Type' : 'application/json',
        },
        body: JSON.stringify(this.state.user)
      });

      const data = await res.json();
      

      if (data.data.length === 0) {
        // user not found in db
        this.setState({user: {...this.state.user}, error: true});
      } else {
        // user logs in successfully: store data in session storage
        const user : {[k: string]: string} = data.data[0];
        for (const [k, v] of Object.entries(user)) {
          sessionStorage.setItem(k, v);
        }
        window.location.href = "/home";
      }
    } catch (error) {
      console.log(error);
    }
  }

  componentDidMount(): void {
      sessionStorage.clear();
  }

  render(): React.ReactNode {
    return (
      <>
        <Head>
          <title>Sign in</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main} style={{
          backgroundImage: `url(${bg.src})`,
          width: '100%',
          height: '100%',
        }}>
          <div className={styles.box}>

            <h1>Sign in</h1>

            <input placeholder='Username' id='username' className={styles.input} onChange={e => this.setState({user: {...this.state.user, username: e.target.value}})} />

            <input placeholder='Password' id='password' className={styles.input} onChange={e => this.setState({user: {...this.state.user, password: e.target.value}})} />

            <button className={styles.submit} onClick={() => this.login()}>Log in</button>

            <p>No account? Register <Link href="/register" className={styles.link} >here</Link></p>

            {this.state.error ? <Popup text='ERROR: Username or password incorrect' color='#de2f2f' onClick={() => this.setState({error: false})} /> : null}
          
          </div>

        </main>
      </>
    )
  }
}

export default Login;
