import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import bg from '../public/shapes.jpg'
import Link from 'next/link'

export default class Home extends React.Component {
  render () {
    return (
      <>
        <Head>
          <title>Sign in</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main} style={{
          backgroundImage: `url(${bg.src})`,
          width: '100%',
          height: '100%',
        }}>
          <div className={styles.box}>

            <h1>Sign in</h1>

            <input placeholder='Username' id='username' className={styles.input} />

            <input placeholder='Password' id='password' className={styles.input} />

            <button className={styles.submit}>Log in</button>

            <p>No account? Register <Link href={"http://example.com/"} style={{color: "rgb(0, 141, 207)"}}>here</Link></p>
          </div>

        </main>
      </>
    )
  }
}
