import React from 'react'
import Head from 'next/head'
import styles from '../styles/NoUser.module.css'
import bg from '../public/shapes.jpg'
import Link from 'next/link'

class Login extends React.Component {
  // store user inputs in state
  state = {
    username: "",
    password: "",
  }

  // check db for user/pass pair
  // admit entry if it exists, reject otherwise
  login = async () => {
    try {
      const res = await fetch('api/query', {
        method: 'POST',
        headers: {
          'Content-Type' : 'application/json',
        },
        body: JSON.stringify(this.state)
      });
      const data = await res.json();
      console.log(data);
      

      if (data.data.length === 0) {
        // user not found in db
        console.log("LOGIN FAILED");
      } else {
        // user logs in successfully
        sessionStorage.setItem("active-user", this.state.username);
        window.location.href = "/home";
      }
    } catch (error) {
      console.log(error);
    }
  };

  render(): React.ReactNode {
    return (
      <>
        <Head>
          <title>Sign in</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main} style={{
          backgroundImage: `url(${bg.src})`,
          width: '100%',
          height: '100%',
        }}>
          <div className={styles.box}>

            <h1>Sign in</h1>

            <input placeholder='Username' id='username' className={styles.input} onChange={e => this.setState({username: e.target.value})} />

            <input placeholder='Password' id='password' className={styles.input} onChange={e => this.setState({password: e.target.value})} />

            <button className={styles.submit} onClick={() => this.login()}>Log in</button>

            <p>No account? Register <Link href="/register" style={{color: "rgb(0, 141, 207)"}}>here</Link></p>
          </div>

        </main>
      </>
    )
  }
}

export default Login;
