import React from "react";
import Head from 'next/head'
import styles from '../styles/NoUser.module.css'
import bg from '../public/shapes.jpg'
import Link from 'next/link'
import Popup from "../components/Popup";

type state = {
  username: string,
  password: string,
  firstName: string,
  lastName: string,
  age: Number,
  error: Boolean,
  errorMsg: string
}

export default class Register extends React.Component {
  state: state = {
    username: "",
    password: "",
    firstName: "",
    lastName: "",
    age: 0,
    error: false,
    errorMsg: ""
  }

  register = async () => {
    if (!this.state.username || !this.state.password) {
      this.setState({error: true});
      this.setState({errorMsg: "ERROR: Username and password requried."});
      return;
    }

    try {
      let newUser: {[k: string]: any} = {};

      for (const [k, v] of Object.entries(this.state)) {
        if (v) {
          newUser[k] = v;
        }
      }

      const res = await fetch('api/append', {
        method: 'POST',
        headers: {
          'Content-Type' : 'application/json',
        },
        body: JSON.stringify(newUser)
      });

      const data = await res.json();
      console.log({ data });

      if (data.error.code === 11000) {
        this.setState({error: true});
        this.setState({errorMsg: "ERROR: Username already taken."});
      }

      // successful if made it this far, log user in
      for (const [k, v] of Object.entries(this.state)) {
        if (k !== "error" && k !== "errorMsg") {
          sessionStorage.setItem(k, String(v));
        }
      }
      window.location.href = "/home";

    } catch (error) {      
      console.log(error);
    }
  }

  render(): React.ReactNode {
    return (
      <>
        <Head>
          <title>Sign up</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main} style={{
            backgroundImage: `url(${bg.src})`,
            width: '100%',
            height: '100%',
          }}>
          <div className={styles.box}>

            <h1>Register</h1>

            <input placeholder='Username (Required)' id='username' className={styles.input} onChange={e => this.setState({username: e.target.value})} />

            <input placeholder='Password (Required)' id='password' className={styles.input} onChange={e => this.setState({password: e.target.value})} />
            
            <input placeholder='First Name (Optional)' id='firstName' className={styles.input} onChange={e => this.setState({firstName: e.target.value})} />
            
            <input placeholder='Last Name (Optional)' id='lastName' className={styles.input} onChange={e => this.setState({lastName: e.target.value})} />
            
            <input placeholder='Age (Optional)' id='age' className={styles.input} onChange={e => this.setState({age: e.target.value})} />

            <button className={styles.submit} onClick={() => this.register()}>Sign up</button>

            <p>Have an account already? Sign in <Link href="/" className={styles.link} >here</Link></p>

            {this.state.error ? <Popup text={this.state.errorMsg} color='#de2f2f' onClick={() => this.setState({error: false, errorMsg: ""})} /> : null}

          </div>

        </main>
      </>
    )
  }
}
