import React, { useState } from "react"
import Head from 'next/head'
import { useRouter } from "next/router"
import Link from 'next/link'
import styles from '../styles/NoUser.module.css'
import bg from '../public/shapes.jpg'
import Popup from "../components/Popup"

const Register: React.FC = () => {
  const router = useRouter();

  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const [firstName, setFirstName] = useState("");
  const [lastName, setLastName] = useState("");
  const [age, setAge] = useState(0);
  const [error, setError] = useState(false);
  const [errorMsg, setErrorMsg] = useState("");
  const [errorCol, setErrorCol] = useState("");

  const signup = async () => {
    if (!(username && password)) {
      setError(true);
      setErrorMsg("ERROR: Username and password requried.");
      setErrorCol("#de2f2f");
      return;
    }

    const userParams = {
      username: username,
      password: password,
      firstName: firstName,
      lastName: lastName,
      age: age,
    };

    let newUser: {[k: string]: any} = {
      notes: []
    };

    for (const [k, v] of Object.entries(userParams)) {
      if (v || k === "notes") {
        newUser[k] = v;
      }
    }

    const res = await fetch('api/register', {
      method: 'POST',
      headers: {
        'Content-Type' : 'application/json',
      },
      body: JSON.stringify(newUser)
    });

    const data = await res.json();

    // successful if made it this far, log user in
    setError(true);
    setErrorMsg("Registration Successful: Please login.");
    setErrorCol("#52be80");

    if ("error" in data && data.error.code === 11000) {
      setError(true);
      setErrorMsg("ERROR: Username already taken.");
      setErrorCol("#de2f2f");
    }

  }

    return (
      <>
        <Head>
          <title>Sign up</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main} style={{
            backgroundImage: `url(${bg.src})`,
            width: '100%',
            height: '100%',
          }}>
          <div className={styles.box}>

            <h1>Register</h1>

            <input placeholder='Username (Required)' id='username' className={styles.input} onChange={e => setUsername(e.target.value)} />

            <input placeholder='Password (Required)' id='password' className={styles.input} onChange={e => setPassword(e.target.value)} />
            
            <input placeholder='First Name (Optional)' id='firstName' className={styles.input} onChange={e => setFirstName(e.target.value)} />
            
            <input placeholder='Last Name (Optional)' id='lastName' className={styles.input} onChange={e => setLastName(e.target.value)} />
            
            <input placeholder='Age (Optional)' id='age' className={styles.input} onChange={e => setAge(parseInt(e.target.value))} />

            <button className={styles.submit} onClick={() => signup()}>Sign up</button>

            <p>Have an account already? Sign in <Link href="/" className={styles.link} >here</Link></p>

            {error ? <Popup text={errorMsg} color={errorCol} onClick={() => {
              setError(false);
              setErrorMsg("");
              setErrorCol("");
              }} /> : null}

          </div>

        </main>
      </>
    )
}

export default Register;
