import React from "react";
import Head from 'next/head'
import styles from '../styles/NoUser.module.css'
import bg from '../public/shapes.jpg'
import Link from 'next/link'

type state = {
  username: String,
  password: String,
  firstName: String,
  lastName: String,
  age: Number,
  showError: Boolean
}

export default class Register extends React.Component {
  state: state = {
    username: "",
    password: "",
    firstName: "",
    lastName: "",
    age: 0,
    showError: false
  }

  register = async () => {
    try {
      let newUser: {[k: string]: any} = {};

      for (const [k, v] of Object.entries(this.state)) {
        if (k !== "error" && v) {
          newUser[k] = v;
        }
      }

      const res = await fetch('api/append', {
        method: 'POST',
        headers: {
          'Content-Type' : 'application/json',
        },
        body: JSON.stringify(newUser)
      });
      const data = await res.json();
      console.log({ data });      

      if (data.error.code === 11000) {
        this.setState({error: true});
        console.log("ERROR: Username already taken.");
      }

    } catch (error) {      
      console.log(error);
    }
  }

  componentDidUpdate(prevState: Readonly<state>): void {
      if (this.state.showError != prevState.showError) {
        // render error msg
      }
  }

  render(): React.ReactNode {
    return (
      <>
        <Head>
          <title>Sign in</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main} style={{
            backgroundImage: `url(${bg.src})`,
            width: '100%',
            height: '100%',
          }}>
          <div className={styles.box}>

            <h1>Register</h1>

            <input placeholder='Username (Required)' id='username' className={styles.input} onChange={e => this.setState({username: e.target.value})} />

            <input placeholder='Password (Required)' id='password' className={styles.input} onChange={e => this.setState({password: e.target.value})} />
            
            <input placeholder='First Name (Optional)' id='firstName' className={styles.input} onChange={e => this.setState({firstName: e.target.value})} />
            
            <input placeholder='Last Name (Optional)' id='lastName' className={styles.input} onChange={e => this.setState({lastName: e.target.value})} />
            
            <input placeholder='Age (Optional)' id='age' className={styles.input} onChange={e => this.setState({age: e.target.value})} />

            <button className={styles.submit} onClick={() => this.register()}>Sign up</button>

            <p>Have an account already? Sign in <Link href="/" style={{color: "rgb(0, 141, 207)"}}>here</Link></p>

          </div>

        </main>
      </>
    )
  }
}
